# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='alias',
        ),
    ]
