# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0002_auto_20170822_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokes',
            name='pokesum',
        ),
        migrations.AddField(
            model_name='users',
            name='pokesum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
