# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='booked_by',
        ),
        migrations.AddField(
            model_name='links',
            name='booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop_app.Items'),
        ),
        migrations.AddField(
            model_name='links',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='shop_app.Users'),
        ),
    ]
