# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20170824_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='totalsum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
