# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt2_app', '0002_auto_20170824_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='added',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='add_by',
        ),
        migrations.AddField(
            model_name='friends',
            name='add_by',
            field=models.ManyToManyField(related_name='add', to='belt2_app.Users'),
        ),
    ]
