# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt2_app', '0003_auto_20170824_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='added',
            field=models.ManyToManyField(related_name='add', to='belt2_app.Users'),
        ),
        migrations.RemoveField(
            model_name='friends',
            name='add_by',
        ),
        migrations.AddField(
            model_name='friends',
            name='add_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addby', to='belt2_app.Users'),
            preserve_default=False,
        ),
    ]
