# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt2_app', '0005_auto_20170824_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='added',
        ),
        migrations.AddField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(related_name='_users_friends_+', to='belt2_app.Users'),
        ),
    ]
