# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0002_auto_20170821_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='liked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='hero_app.Users'),
            preserve_default=False,
        ),
    ]
