# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0003_heroes_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroes',
            name='liked',
        ),
        migrations.AddField(
            model_name='heroes',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', to='hero_app.Users'),
        ),
    ]
